# Generated by Django 5.1.1 on 2024-10-11 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycoach', '0001_initial'),
        ('rutinas', '0002_delete_comentarioentrenamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.rutina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mycoach.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='ValoracionPersonal',
        ),
    ]
