# Generated by Django 5.1.1 on 2024-11-13 18:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutricion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comida', models.CharField(max_length=100)),
                ('calorias', models.IntegerField(help_text='Cantidad de calorías por 100g', validators=[django.core.validators.MinValueValidator(0)])),
                ('proteinas', models.DecimalField(decimal_places=2, help_text='Gramos de proteína por 100g', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('grasas', models.DecimalField(decimal_places=2, help_text='Gramos de grasas por 100g', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('carbohidratos', models.DecimalField(decimal_places=2, help_text='Gramos de carbohidratos por 100g', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('porcion_recomendada', models.DecimalField(decimal_places=2, default=100.0, help_text='Porción recomendada en gramos', max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
                'ordering': ['nombre_comida'],
            },
        ),
        migrations.CreateModel(
            name='TipoRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Rutina',
                'verbose_name_plural': 'Tipos de Rutinas',
                'ordering': ['nombre_tipo'],
            },
        ),
        migrations.CreateModel(
            name='DetallePlanNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad en gramos', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rutinas.nutricion')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PlanNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_plan', models.DateField()),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alimentos', models.ManyToManyField(through='rutinas.DetallePlanNutricional', to='rutinas.nutricion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_nutricionales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan Nutricional',
                'verbose_name_plural': 'Planes Nutricionales',
                'ordering': ['-fecha_plan'],
                'unique_together': {('usuario', 'fecha_plan')},
            },
        ),
        migrations.AddField(
            model_name='detalleplannutricional',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='rutinas.plannutricional'),
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='sin nombre', max_length=200)),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], default='Principiante', max_length=20)),
                ('duracion_estimada', models.DurationField(default=0, help_text='Duración estimada de la rutina')),
                ('calorias_estimadas', models.PositiveIntegerField(blank=True, help_text='Calorías estimadas a quemar', null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('usuario_creador', models.ForeignKey(default='no se conoce', on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_creadas', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='rutinas.tiporutina', verbose_name='Tipo de Rutina')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Entrenador', 'Entrenador'), ('Deportista', 'Deportista')], max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateField()),
                ('duracion_minutos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(480)])),
                ('calorias_quemadas', models.PositiveIntegerField(blank=True, help_text='Calorías estimadas quemadas durante la rutina', null=True)),
                ('nivel_esfuerzo', models.IntegerField(default=1, help_text='Nivel de esfuerzo percibido (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('completada', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales_rutina', to=settings.AUTH_USER_MODEL)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='rutinas.rutina')),
            ],
            options={
                'verbose_name': 'Historial de Rutina',
                'verbose_name_plural': 'Historiales de Rutina',
                'ordering': ['-fecha_realizacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateField()),
                ('progreso', models.CharField(max_length=100)),
                ('observaciones', models.TextField()),
                ('rol', models.CharField(choices=[('Participante', 'Participante'), ('Observador', 'Observador'), ('Coach', 'Coach')], max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Entrenador', 'Entrenador'), ('Deportista', 'Deportista')], max_length=15)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10)),
                ('peso_actual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='detalleplannutricional',
            unique_together={('plan', 'alimento')},
        ),
        migrations.CreateModel(
            name='EjercicioEnRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ejercicio', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('series', models.PositiveIntegerField()),
                ('repeticiones', models.PositiveIntegerField()),
                ('descanso', models.DurationField(help_text='Tiempo de descanso entre series')),
                ('orden', models.PositiveIntegerField(help_text='Orden del ejercicio en la rutina')),
                ('notas', models.TextField(blank=True)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='rutinas.rutina')),
            ],
            options={
                'verbose_name': 'Ejercicio en Rutina',
                'verbose_name_plural': 'Ejercicios en Rutina',
                'ordering': ['orden'],
                'unique_together': {('rutina', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='ValoracionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_valoracion', models.DateField()),
                ('masa_corporal', models.DecimalField(decimal_places=2, default=0, help_text='Peso en kilogramos', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('30.00')), django.core.validators.MaxValueValidator(Decimal('300.00'))])),
                ('grasa_corporal', models.DecimalField(decimal_places=2, help_text='Porcentaje de grasa corporal', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('3.00')), django.core.validators.MaxValueValidator(Decimal('60.00'))])),
                ('agua_corporal', models.DecimalField(decimal_places=2, help_text='Porcentaje de agua corporal', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('20.00')), django.core.validators.MaxValueValidator(Decimal('80.00'))])),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valoración Personal',
                'verbose_name_plural': 'Valoraciones Personales',
                'ordering': ['-fecha_valoracion'],
                'unique_together': {('usuario', 'fecha_valoracion')},
            },
        ),
    ]
