# Generated by Django 5.1.1 on 2024-10-11 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComentarioEntrenamiento',
        ),
    ]
