# Generated by Django 5.1.1 on 2024-10-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0003_ejercicio_nutricion_tiporutina_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
