# Generated by Django 5.1.1 on 2024-10-29 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0005_coach_deportista'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComentariosEntrenamientos',
            new_name='ComentarioEntrenamiento',
        ),
        migrations.RemoveField(
            model_name='deportista',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='masasegmental',
            name='valoracion',
        ),
        migrations.RemoveField(
            model_name='rutinacalentamiento',
            name='ejercicio',
        ),
        migrations.RemoveField(
            model_name='rutinacalentamiento',
            name='rutina',
        ),
        migrations.RemoveField(
            model_name='rutinaentrenamientoprincipal',
            name='ejercicio',
        ),
        migrations.RemoveField(
            model_name='rutinaentrenamientoprincipal',
            name='rutina',
        ),
        migrations.RemoveField(
            model_name='rutinaestiramiento',
            name='ejercicio',
        ),
        migrations.RemoveField(
            model_name='rutinaestiramiento',
            name='rutina',
        ),
        migrations.RemoveField(
            model_name='valoracionespersonales',
            name='usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='altura',
            new_name='peso_actual',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='tipo_rutina',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='peso',
        ),
        migrations.AddField(
            model_name='rutina',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rutinas.tiporutina'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='altura_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='tipo',
            field=models.CharField(choices=[('Calentamiento', 'Calentamiento'), ('Estiramiento', 'Estiramiento'), ('EntrenamientoPrincipal', 'Entrenamiento Principal')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Entrenador', 'Entrenador'), ('Deportista', 'Deportista')], max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10),
        ),
        migrations.CreateModel(
            name='DetalleRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateField()),
                ('progreso', models.CharField(max_length=100)),
                ('observaciones', models.TextField()),
                ('rol', models.CharField(choices=[('Participante', 'Participante'), ('Observador', 'Observador'), ('Coach', 'Coach')], max_length=20)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.rutina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateField()),
                ('duracion_minutos', models.IntegerField()),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.rutina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipanteRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Entrenador', 'Entrenador'), ('Deportista', 'Deportista')], max_length=20)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.rutina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PlanNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_plan', models.DateField()),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.nutricion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_minutos', models.IntegerField()),
                ('series', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='ValoracionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_valoracion', models.DateField()),
                ('masa_segmental', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grasa_corporal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('agua_corporal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
        migrations.DeleteModel(
            name='Deportista',
        ),
        migrations.DeleteModel(
            name='MasaSegmental',
        ),
        migrations.DeleteModel(
            name='RutinaCalentamiento',
        ),
        migrations.DeleteModel(
            name='RutinaEntrenamientoPrincipal',
        ),
        migrations.DeleteModel(
            name='RutinaEstiramiento',
        ),
        migrations.DeleteModel(
            name='ValoracionesPersonales',
        ),
    ]
