# Generated by Django 5.1.1 on 2024-11-10 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0006_rename_comentariosentrenamientos_comentarioentrenamiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valoracionpersonal',
            old_name='masa_segmental',
            new_name='masa_corporal',
        ),
    ]
